version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # Persistent storage on host
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - app_network
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=2GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  app_network:
    driver: bridge