# Generated by Django 5.1.3 on 2024-11-29 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('dataset', models.CharField(max_length=255)),
                ('feedback', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree'), ('uncertain', 'Uncertain')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['search_term', 'dataset'], name='feedback_fe_search__ecd8e7_idx')],
                'unique_together': {('user', 'search_term', 'dataset')},
            },
        ),
    ]
