# Generated by Django 5.1.3 on 2024-11-29 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_fe_search__ecd8e7_idx',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree'), ('uncertain', 'Uncertain')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='dataset',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='feedbackvote',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedback'),
        ),
        migrations.AddField(
            model_name='feedbackvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.AlterUniqueTogether(
            name='feedbackvote',
            unique_together={('user', 'feedback')},
        ),
    ]
