# Generated by Django 5.1.3 on 2025-01-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree'), ('uncertain', 'Uncertain')], default='uncertapubin', max_length=20),
        ),
    ]
