# Generated by Django 5.1.3 on 2024-11-29 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackvote_alter_feedback_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['search_term', 'dataset'], name='feedback_fe_search__ecd8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user', 'search_term', 'dataset'], name='feedback_fe_user_id_7126de_idx'),
        ),
    ]
